---
- hosts: localhost
  tasks:
#  - name: install epel repository
#    become: yes
#    package:
#      name: epel-release
#      state: present
  
  - name: install dependencies
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - python-pip
    - gcc
    - python-devel
  
  - name: install python libraries
    become: yes
    pip:
      name: "{{ item }}"
      state: present
    with_items:
    - flask
    - flask-sqlalchemy
    - flask-migrate
    - uwsgi
  
#  - name: get the application code
#    become: yes
#    git:
#      repo: git@github.com:ansible-cookbook/phonebook-sqlite.git
#      dest: /opt/phone-book
  
  - name: upload systemd unit file
    become: yes
    copy:
      src: phone-book.service
      dest: /etc/systemd/system/phone-book.service
  
  - name: start phonebook
    become: yes
    systemd:
      state: started
      daemon_reload: yes
      name: phone-book
      enabled: yes
